config/routes.rb
Rails.application.routes.draw do
  get 'index' => "events#index"

  get 'new' => "events#new", as: 'new_event'

  post 'new' => 'events#new'

  get 'edit/:id' => "events#edit", as: 'edit_event'

  post 'edit/:id' => 'events#edit'

  get 'event/:id' => "events#show", as: 'event'

  get 'profile' => 'pages#profile'

  get 'privacy' => 'pages#privacy'

  get 'terms' => 'pages#terms'

  delete 'delete/:id' => "events#destroy", as: 'destroy_event'

  patch 'event/:id' => "events#update"

  get 'confirmed' => 'pages#confirmed', as: 'confirmed'

 root 'events#index'

 resources :events

 devise_for :users, controllers: { confirmations: 'confirmations', omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations', passwords: 'passwords' }

  devise_scope :user do
    
    get 'login' => 'devise/sessions#new', as: 'login'

    post 'login' => 'devise/sessions#create'

    get 'register' => 'devise/registrations#new', as: 'register'

    post 'register' => 'devise/registrations#create'

    get 'profile/edit' => 'devise/registrations#edit', as: 'edit_user'

    get 'user/city' => 'registrations#city', as: 'add_city'

    get 'profile/password/edit' => 'registrations#edit_password', as: 'edit_password'

    patch 'user/password' => 'registrations#update_password' 

    patch 'user/city' => 'registrations#update_city'

    get 'password/reset' => 'passwords#new', as: 'password_reset'

    post 'password/reset' => 'passwords#reset_password'

    post 'email/confirmations' => 'confirmations#send_confirmation', as: 'send_reconfirmation'

    get 'email/confirmations' => 'confirmations#send_confirmation'

  end

  namespace :api, defaults: { format: :json } do
  namespace :v1 do
    devise_scope :user do
      #posts
      post 'register' => 'registrations#create'
      post 'login' => 'sessions#create'
      post 'facebook/login' => 'omniauth_callbacks#facebook'
      #puts
      put 'update' => 'registrations#update'
      #deletes
      delete 'logout' => 'sessions#destroy'
    end

    get 'email/:email' => 'miscs#email_search', :constraints => { :email => /.*/ }

    get 'events/:today/:city' => 'events#get_events'

    get 'event/show/:id' => 'events#show'

    post 'password/reset/:email' => 'miscs#reset_password', :constraints => { :email => /.*/ }

  end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

	serialize :recurring, Hash 

	attr_accessor :hour, :minute, :meridiem, :endhour, :endminute, :endmeridiem

	validates_presence_of :title, :description, :address, :category, :time, :cover_image
	validates_length_of :title, maximum: 75
	validates_length_of :description, maximum: 1000
	validates_length_of :address, maximum: 100
	validates_length_of :url, maximum: 500
	validates :endtime, presence: true, allow_blank: true
	validates :enddate, presence: true, allow_blank: true
  validates :date, presence: true, allow_blank: true

	belongs_to :user

	geocoded_by :address

	after_validation :geocode, :if => :address_changed?

	after_validation :found_address_presence

	before_validation :parse_time, :parse_endtime, :valid_date,
   :date_is_present, :smart_add_url_protocol, :valid_time

	mount_uploader :cover_image, CoverImageUploader

  def recurring=(value)
    if RecurringSelect.is_valid_rule?(value)
        super(RecurringSelect.dirty_hash_to_rule(value).to_hash)
    else
        super(nil)
    end
  end

	def parse_time
    	if hour and minute and meridiem
   			self.time = DateTime.parse("#{hour}:#{minute}#{meridiem}") 
  		end
	end

	def parse_endtime
    	if endhour and endminute and endmeridiem
   			self.endtime = DateTime.parse("#{endhour}:#{endminute}#{endmeridiem}") 
  		else
  			self.endtime = nil
  		end
	end

	def found_address_presence
    	if latitude.blank? || longitude.blank?
      		self.errors.add(:address, :invalid, message: "Address is not valid")
    	end
  	end

  	def valid_date
  		if enddate && date
  			if self.enddate < self.date
  				self.errors.add(:enddate, "End date is before start date")
  			end
  		end
  	end

    def valid_time
      if endtime
        if endtime.strftime("%H%M") <= time.strftime("%H%M")
          self.errors.add(:endtime, "End time can't be before or the same as the start time")
        end
      end
    end

    def date_is_present
      if recurring.blank?
        if date.blank?
          self.errors.add(:date, "One time events must have a start date")
        end
      end
    end

    def smart_add_url_protocol
      if !url.blank?
        unless self.url[/\Ahttp:\/\//] || self.url[/\Ahttps:\/\//]
          self.url = "http://#{self.url}"
        end
      end
    end

    #ice cube methods

    def rule
      IceCube::Rule.from_hash recurring 
    end 

    def schedule(start)
        schedule = IceCube::Schedule.new(start)
        schedule.add_recurrence_rule(rule)
        schedule
    end 

    def calender(start)
      if recurring.empty?
        [self]
      else
          start_date = start
          end_date = start 
          schedule(start_date).occurrences(end_date).map do |date|
              self
          end
      end
    end

end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController

def get_events
	@city = params[:city]
	@events = Event.near(@city, 100)
	@date = params[:today]
	@events = Event.where('(date = ? AND enddate IS NULL) OR (date <= ? AND enddate >= ?) OR (date IS NULL AND enddate IS NULL) OR (date IS NULL AND enddate >= ?)', 
	      @date, @date, @date, @date)
	@events = @events.flat_map{ |e| e.calender(@date) }
	render json: {
		events: @events
	}
end

def show
	@event = Event.find_by(id: param[:id])
	render json: {
		event: @event
	}
end

def profile
	@user = current_user
	@city = @user.city
	@name = @user.name
	@posts = current_user.events.order('created_at DESC').paginate(page: params[:page], per_page: 10)
end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

before_action :authenticate_user!
before_action :confirmed, only: [:new, :create, :edit, :update, :destroy]

require 'will_paginate/array'

  def index
    if params[:search].present?
      @city = params[:search]
      #filter events  
      @events = Event.near(@city, 100)
      if params[:date_filter]
        date_filter = params[:date_filter]
       begin
          @date = Date.new date_filter["(1i)"].to_i, date_filter["(2i)"].to_i, date_filter["(3i)"].to_i
          @events = Event.where('(date = ? AND enddate IS NULL) OR (date <= ? AND enddate >= ?) OR (date IS NULL AND enddate IS NULL) OR (date IS NULL AND enddate >= ?)', 
              @date, @date, @date, @date)
          @events = @events.flat_map{ |e| e.calender(@date) }
        rescue ArgumentError
          @events = Event.where('(date = ? AND enddate IS NULL) OR (date <= ? AND enddate >= ?) OR (date IS NULL AND enddate IS NULL) OR (date IS NULL AND enddate >= ?)', 
              Date.current, Date.current, Date.current, Date.current).near(@city, 100)
          @events = @events.flat_map{ |e| e.calender(Date.current) }
        end
       else
        @events = Event.where('(date = ? AND enddate IS NULL) OR (date <= ? AND enddate >= ?) OR (date IS NULL AND enddate IS NULL) OR (date IS NULL AND enddate >= ?)', 
            Date.current, Date.current, Date.current, Date.current).near(@city, 100)
        @events = @events.flat_map{ |e| e.calender(Date.current) }
      end
    else
      @city = current_user.city
      #filter events  
      @events = Event.near(@city, 100)
      if params[:date_filter]
        date_filter = params[:date_filter]
        begin
          @date = Date.new date_filter["(1i)"].to_i, date_filter["(2i)"].to_i, date_filter["(3i)"].to_i
          @events = Event.where('(date = ? AND enddate IS NULL) OR (date <= ? AND enddate >= ?) OR (date IS NULL AND enddate IS NULL) OR (date IS NULL AND enddate >= ?)', 
              @date, @date, @date, @date)
          @events = @events.flat_map{ |e| e.calender(@date) }
        rescue
          @events = Event.where('(date = ? AND enddate IS NULL) OR (date <= ? AND enddate >= ?) OR (date IS NULL AND enddate IS NULL) OR (date IS NULL AND enddate >= ?)', 
              Date.current, Date.current, Date.current, Date.current).near(@city, 100)
          @events = @events.flat_map{ |e| e.calender(Date.current) }
        end
      else
        @events = Event.where('(date = ? AND enddate IS NULL) OR (date <= ? AND enddate >= ?) OR (date IS NULL AND enddate IS NULL) OR (date IS NULL AND enddate >= ?)', 
            Date.current, Date.current, Date.current, Date.current).near(@city, 100)
        @events = @events.flat_map{ |e| e.calender(Date.current) }
      end
    end
    @events = @events.select{|event| event.category == params[:with_category]} unless params[:with_category].blank?
     #paginate results
    @events = @events.paginate(page: params[:page], per_page: 10)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
       redirect_to event_path(@event.id)
       flash[:notice] = "Event successfully created."
    else
      render 'new'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if current_user = @event.user
      @event.destroy
      flash[:notice] = "Event successfully deleted."
    end
      redirect_to profile_path
  end

  def show
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if !params[:event].has_key?(:enddate)
        @event.enddate = nil
    end

    if !params[:event].has_key?(:date)
        @event.date = nil
    end

    if current_user = @event.user
      if @event.update(event_params)
        redirect_to event_path(@event.id)
        flash[:notice] = "Changes saved successfully."
      else
        render 'edit'
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  private

  def confirmed
    if current_user.email == current_user.unconfirmed_email || !current_user.confirmed?
      flash[:alert] = "Please verify your email."
      redirect_to root_path
   end
  end

  def event_params
    params.require(:event).permit(:title, :description, :cover_image, 
      :category, :url, :date, :enddate, 
      :address, :hour, :minute, :meridiem,
      :endhour, :endminute, :endmeridiem, :recurring)
  end

end

app/helpers/events_helper.rb
module EventsHelper
	def audio_path(source, options = {})
    path_to_asset(source, {type: :audio}.merge!(options))
end
end

app/views/events/_date.html.erb
<div class="date">
  <%= f.label :Start_Date %><br>
  <%= f.date_select :date, start_year: Date.current.year, end_year: Date.current.year + 5%>
</div>

app/views/events/_enddate.html.erb
<div class="enddate">
  <%= f.label :end_date%><br>
  <%= f.date_select :enddate, start_year: Date.current.year, end_year: Date.current.year + 5 %>
</div>

app/views/events/_endtime.html.erb
<div class="endtime">
  <%= f.label :End_time %><br>

  <% if @event.endtime? %>

  <%= f.select :endhour, [["1", "01"], ["2", "02"], ["3","03"], ["4", "04"], ["5", "05"], ["6", "06"], ["7", "07"], ["8", "08"], ["9", "09"], "10", "11", "12"], selected: @event.endtime.strftime("%I")%> :

  <%= f.select :endminute, ["00", "15", "30", "45"], selected: @event.endtime.strftime("%M") || "00" %> 

  <%= f.select :endmeridiem, ["AM", "PM"], selected: @event.endtime.strftime("%p") || "AM" %> <br>

  <% else %>

    <%= f.select :endhour, [["1", "01"], ["2", "02"], ["3","03"], ["4", "04"], ["5", "05"], ["6", "06"], ["7", "07"], ["8", "08"], ["9", "09"], "10", "11", "12"]%> :

  <%= f.select :endminute, ["00", "15", "30", "45"] %> 

  <%= f.select :endmeridiem, ["AM", "PM"]%> <br>

<% end %>

</div>

app/views/events/_event.html.erb
<%= div_for event, :class => "event-item" do %>
	<%= link_to event_path(event.id) do %>
		<%= image_tag event.cover_image.to_s %>
		<div class="title"><%= event.title %></div>
	<% end %>
<% end %> 

<script type="text/javascript">
	
	$(document).ready(function(){
	$('.title').each(function(){
		var height = $(this).height();
		$(this).css("bottom", height + "px");
	});
});

</script>

app/views/events/edit.html.erb
<% if flash.now[:alert] %>
<div class="messages-confirm">
    <div class="alert alert-success">
      <%= flash[:alert] %> 
      <%= link_to 'Send confirmation email', send_confirmation_url %>
    </div>
</div>
<% end %>

<div class='user-form'>
<h3>Edit event</h3>

<%= form_for @event do |f| %>

<% if @event.errors.present? %>
 <div id="error_explanation">
    <div class="alert alert-danger">
      <ul>
        <% @event.errors.each do |field, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="image-error">
</div>

<% if @event.cover_image? %>
  <div class="cover-image-container">
      <span id="image">
          <img src="<%= @event.cover_image.to_s %>"/>
      </span>
  </div>
<% else %>

 <div class="cover-image-container">
      <span id="image"></span>
       <div class="cover-image-text"> 
      <span class="fa fa-photo"></span>
      Add a cover image <br><span>(750 x 375 for optimal dimensions)</span></div>
  </div>

<% end %>


  <div class="form-field">
    <%= f.text_field :title, :placeholder => 'Title' %>
  </div>

  <div class="form-field">
  <%= f.text_area :description, :placeholder => 'Description' %> 
  </div>

  <%= f.file_field :cover_image, id: 'upload'%>

  <div class="form-field">
    <%= f.text_field :address, :placeholder => 'Address or Place', class: 'location-field' %>
  </div>

  <div class="form-field">
  <%= f.text_field :url, :placeholder => 'Event website (optional)' %>
  </div>

  <div class="form-field">
  <%= f.label :Category %><br>
  <%= f.select :category, ['Activities & Attractions','Art', 'Bars, Pubs & Clubs', 'Educational', 'Entertainment', 'Family', 'Fitness', 'Food & Drinks', 'Fundraising', 'Music', 'Outdoor Recreation', 'Religious','Shopping', 'Sports', 'Tours', 'Other'] %>
  </div>

<div class="form-field">
  <%= f.label :Recurring %><br>
  <%= f.select_recurring :recurring, nil, :allow_blank => true %>
</div>

<% if @event.date? %>

  <%= render partial: 'events/date', locals: {f: f} %>

<% end %>

<div class="date-container">
</div>

<div class="add-date">
  + Add a date or start date
</div>

<div class="remove-date">
   Remove start date
</div>


<% if @event.enddate? %>

  <%= render partial: 'events/enddate', locals: {f: f} %>

<% end %>

<div class="enddate-container">
</div>

<div class="add-enddate">
  + Add end date
</div>

<div class="remove-enddate">
   Remove end date
</div>

<div class="form-field">
<%= f.label :Start_time %><br>
<%= f.select :hour, [["1", "01"], ["2", "02"], ["3","03"], ["4", "04"], ["5", "05"], ["6", "06"], ["7", "07"], ["8", "08"], ["9", "09"], "10", "11", "12"], selected: @event.time.strftime('%I')%> :

  <%= f.select :minute, ["00", "15", "30", "45"], selected: @event.time.strftime("%M")%> 

  <%= f.select :meridiem, ["AM", "PM"], selected: @event.time.strftime("%p")%> <br>
</div>

<% if @event.endtime? %>

  <%= render partial: 'events/endtime', locals: {f: f} %>

<% end %>

<div class="endtime-container">
</div>

<div class="add-endtime">
+ Add end time
</div>

<div class="remove-endtime">
Remove end time
</div>

  <%= f.submit "Save Changes", id: 'submit' %>

<script>

if($('.date').length != 0){
    $('.add-date').hide();
    $('.remove-date').show();
} else {
    $('.add-date').show();
    $('.remove-date').hide();
}

if($('.endtime').length != 0){
    $('.add-endtime').hide();
    $('.remove-endtime').show();
} else {
    $('.add-endtime').show();
    $('.remove-endtime').hide();
}

if($('.enddate').length != 0){
    $('.add-enddate').hide();
    $('.remove-enddate').show();
} else {
    $('.add-enddate').show();
    $('.remove-enddate').hide();
}

 $('.add-date').click(function(){
    $('.date-container').append("<%= j render partial: 'events/date', locals: {f: f} %>");
    $('.date').show("fast");
    $('.add-date').hide();
    $('.remove-date').show();
  });

  $('.remove-date').click(function(){
    $('.date').remove();
    $('.add-date').show();
    $('.remove-date').hide();
  });

 $('.add-endtime').click(function(){
    $('.endtime-container').append("<%= j render partial: 'events/endtime', locals: {f: f} %>");
    $('.endtime').show("fast");
    $('.add-endtime').hide();
    $('.remove-endtime').show();
  });

  $('.remove-endtime').click(function(){
    $('.endtime').remove();
    $('.add-endtime').show();
    $('.remove-endtime').hide();
  });

  $('.add-enddate').click(function(){
    $('.enddate-container').append("<%= j render partial: 'events/enddate', locals: {f: f} %>");
    $('.enddate').show("fast");
    $('.add-enddate').hide();
    $('.remove-enddate').show();
  });

  $('.remove-enddate').click(function(){
    $('.enddate').remove();
    $('.add-enddate').show();
    $('.remove-enddate').hide();
  });
</script>

<% end %>
</div>

app/views/events/index.html.erb
<% if flash.now[:alert] %>
<div class="messages-confirm">
    <div class="alert alert-success alert-dismissible">
    	<%= flash[:alert] %> 
    	<%= link_to 'Send confirmation email', send_reconfirmation_path(current_user) %>
    </div>
</div>
<% end %>

<% if flash.now[:notice] %>
<div class="messages">
    <div class="alert alert-info">
    	<%= flash[:notice] %>
    </div>
</div>
<% end %>

<div class="index">

<div class="search-filters">
<div class="filter-fields">
	<%= form_tag events_path, :method => :get do %>
        <%= hidden_field_tag :search, params[:search] %>
        <div class="form-field">
			<%= label :date, 'Date' %><br>
	        <%= date_select :date_filter, '' , start_year: Date.current.year, end_year: Date.current.year + 5, prompt: true %>
		</div>

          <div class="form-field">
			  <%= label :Category, 'Category' %><br>
			  <%= select_tag :with_category, options_for_select(['Activities & Attractions', 'Art', 'Bars, Pubs & Clubs', 'Educational', 'Entertainment', 'Family', 'Fitness', 'Food & Drinks', 'Fundraising', 'Music', 'Outdoor Recreation', 'Religious','Shopping', 'Sports', 'Tours', 'Other'], params[:with_category]), :prompt => "All categories" %>
		  </div>
            
            <div class="actions">
            <%= submit_tag "Apply filters", class: "btn btn-primary filter-btn", name: 'filter'%> 
            </div>
    <% end %>
</div>
</div>

	<div class="feed">
		<div class="results">
		<% if @events.count == 0 %>
			<% if @date || params[:with_category]%>
				0 events
				<% if @date %> 
				<%= ' happening ' + @date.strftime("%B, %-d, %Y") %>
				<%= 'in ' + params[:with_category] unless params[:with_category].blank? %>
				<% else %>
				happening
				<%= 'in ' + params[:with_category] unless params[:with_category].blank? %>  
				today
				<% end %>
			<% else %>
				No events found
			<% end %>
		<% else %>
			<%= number_with_delimiter(@events.count) %>
			<% if @events.count > 1 %>
				events
			<% else %>
				event
			<% end %>

			<% if @date %> 
			<%= ' happening ' + @date.strftime("%B, %-d, %Y") %>
			<%= 'in ' + params[:with_category] unless params[:with_category].blank? %>
			<% else %>
			happening
			<%= 'in ' + params[:with_category] unless params[:with_category].blank? %>
			today  
			<% end %>
		<% end %>
		</div>

		<div class="events">
			<%= render @events %>
		</div>
		<div class="pagination">
			<%= will_paginate @events %>
		</div>
		<% if @events.next_page %>
			<div id="load-more-posts" class="btn btn-primary"> Load more posts</div>
		<% end %>
	</div>
</div>

app/views/events/index.js.erb
$('.events').append('<%= j render @events %>');
<% if @events.next_page %>
   $('.pagination').replaceWith('<%= j will_paginate @events %>');
   $('.pagination').hide();
<% else %>
	$('.pagination').remove();
	$('#load-more-posts').remove();
<% end %>

app/views/events/new.html.erb
<% if flash.now[:alert] %>
<div class="messages-confirm">
    <div class="alert alert-success">
      <%= flash[:alert] %> 
      <%= link_to 'Send confirmation email', send_confirmation_url %>
    </div>
</div>
<% end %>

<div class='user-form'>
<h3>Create new event</h3>

<%= form_for @event do |f| %>

<% if @event.errors.present? %>
 <div id="error_explanation">
    <div class="alert alert-danger">
      <ul>
        <% @event.errors.each do |field, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="image-error">
</div>

  <div class="cover-image-container">
      <span id="image"></span>
       <div class="cover-image-text"> 
      <span class="fa fa-photo"></span>
      Add a cover image <br><span>(750 x 375 for optimal dimensions)</span></div>
  </div>

  <div class="form-field">
    <%= f.text_field :title, :placeholder => 'Title' %>
  </div>

  <div class="form-field">
  <%= f.text_area :description, :placeholder => 'Description' %> 
  </div>

  <%= f.file_field :cover_image, id: 'upload'%>

  <div class="form-field">
    <%= f.text_field :address, class:'location-field', :placeholder => 'Address or Place' %>
  </div>

  <div class="form-field">
  <%= f.text_field :url, :placeholder => 'Event website (optional)' %>
  </div>

  <div class="form-field">
  <%= f.label :Category %><br>
  <%= f.select :category, ['Activities & Attractions', 'Art', 'Bars, Pubs & Clubs', 'Educational', 'Entertainment', 'Family', 'Fitness', 'Food & Drinks', 'Fundraising', 'Music', 'Outdoor Recreation', 'Religious', 'Shopping', 'Sports', 'Tours', 'Other'] %>
  </div>

<div class="form-field">
  <%= f.label :Recurring %><br>
  <%= f.select_recurring :recurring %>
</div>

<div class="date-container">
</div>

<div class="add-date">
  + Add a date or start date
</div>

<div class="remove-date">
   Remove start date
</div>

<div class="enddate-container">
</div>

<div class="add-enddate">
  + Add an end date
</div>

<div class="remove-enddate">
   Remove end date
</div>

<div class="form-field">
<%= f.label :Start_time %><br>
<%= f.select :hour, ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]%> :

  <%= f.select :minute, ["00", "15", "30", "45"]%> 

  <%= f.select :meridiem, ["AM", "PM"]%> <br>
</div>

<div class="endtime-container">
</div>

<div class="add-endtime">
+ Add end time
</div>

<div class="remove-endtime">
Remove end time
</div>

  <%= f.submit "Create Event", id: 'submit' %>

<script>

 $('.add-date').click(function(){
    $('.date-container').append("<%= j render partial: 'events/date', locals: {f: f} %>");
    $('.date').show("fast");
    $('.add-date').hide();
    $('.remove-date').show();
  });

  $('.remove-date').click(function(){
    $('.date').remove();
    $('.add-date').show();
    $('.remove-date').hide();
  });


 $('.add-endtime').click(function(){
    $('.endtime-container').append("<%= j render partial: 'events/endtime', locals: {f: f} %>");
    $('.endtime').show("fast");
    $('.add-endtime').hide();
    $('.remove-endtime').show();
  });

  $('.remove-endtime').click(function(){
    $('.endtime').remove();
    $('.add-endtime').show();
    $('.remove-endtime').hide();
  });

  $('.add-enddate').click(function(){
    $('.enddate-container').append("<%= j render partial: 'events/enddate', locals: {f: f} %>");
    $('.enddate').show("fast");
    $('.add-enddate').hide();
    $('.remove-enddate').show();
  });

  $('.remove-enddate').click(function(){
    $('.enddate').remove();
    $('.add-enddate').show();
    $('.remove-enddate').hide();
  });
</script>

<% end %>
</div> 

app/views/events/show.html.erb
<% if flash.now[:notice] %>
<div class="messages">
    <div class="alert alert-info">
    	<%= flash[:notice] %>
    </div>
</div>
<% end %>

<div class="show-container">
<div class="show-item">

	<div class="cover-image">
		<%= image_tag @event.cover_image %>
		<% if current_user == @event.user %>

 		<div class="controls">
 		
 		<%= link_to edit_event_path(@event.id), class: 'btn btn-primary' do%>
 		Edit <span class="fa fa-pencil"></span>
 		<% end %>

	 	<%= link_to destroy_event_path(@event), method: :delete, class: 'btn btn-danger', data:{:confirm => 'Are you sure you want to delete this event?'} do %>
  		Delete <span class="fa fa-trash-o"></span>
  		<% end %>
  		</div>
	<% end %>
	</div>
	<div></div>
	<div class="show-title"><%= @event.title %></div>

	<hr>

	  <strong>Location:</strong>
	  <%= @event.address %>
	  <div class="show-map">Show on map</div>

	<div class="map"><%= image_tag "https://maps.google.com/maps/api/staticmap?size=500x250&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}" %></div>

	<div class="time">

		<% if @event.endtime? %>

		<strong>Time: </strong><%= @event.time.strftime("%l:%M%P")%> - <%= @event.endtime.strftime("%l:%M%P")%>

		<% else %>

		<strong>Start time: </strong><%= @event.time.strftime("%l:%M%P")%>

		<% end %>

		<div class="recurring">
			<% if @event.recurring.empty? %>
				<strong>Date: </strong><%= @event.date.strftime("%B, %-d, %Y") %>

				<% if @event.enddate? %>
					- <%= @event.enddate.strftime("%B, %-d, %Y") %>
				<% end %>

			<% else %>
				<strong>Days: </strong><%= IceCube::Rule.from_hash(@event.recurring) %>

				<div>
				<% if @event.date? && @event.enddate? %>
					<strong>Dates: </strong><%= @event.date.strftime("%B, %-d, %Y") %> - <%= @event.enddate.strftime("%B, %-d, %Y") %>
				<% else %>

				<div>
				<% if @event.date? %>
					<strong>Starts: </strong><%= @event.date.strftime("%B, %-d, %Y") %>
				<% end %>
				</div>

				<div>
				<% if @event.enddate? %>
					<strong>Ends: </strong><%= @event.enddate.strftime("%B, %-d, %Y") %>
				<% end %>
				</div>

				<% end %>
				</div>
			<% end %>

		</div>

	</div>

	<% if @event.url? %>

		<strong>Website: </strong><%= link_to @event.url, @event.url, target: '_blank'%>

	<% end %>

	<div>
	<strong>Category: </strong><%= @event.category %>
	</div>

	<hr>

	<strong>Description:</strong><br>
	<%= simple_format(@event.description) %>
</div>

<div class="nearby-events">

<div class="nearby-title">Nearby events happening today</div>

<% if @event.nearbys(20).where('(date = ? AND enddate IS NULL) OR (date <= ? AND enddate >= ?) OR (date IS NULL AND enddate IS NULL) OR (date IS NULL AND enddate >= ?)', 
        Date.current, Date.current, Date.current, Date.current).limit(5).flat_map{ |e| e.calender(params.fetch(:date, Time.current).to_date) }.empty? %>

<div class='no-events'>No events happening today :(</div>

<% else %>
	<% for event in @event.nearbys(20).where('(date = ? AND enddate IS NULL) OR (date <= ? AND enddate >= ?) OR (date IS NULL AND enddate IS NULL) OR (date IS NULL AND enddate >= ?)', 
        Date.current, Date.current, Date.current, Date.current).limit(5).flat_map{ |e| e.calender(params.fetch(:date, Time.current).to_date) } %>
		<%= div_for event, :class => "nearby-event-items" do %>
			<%= link_to event_path(event.id) do %>
				<%= image_tag event.cover_image.to_s %>
				<div class="title"><%= event.title %></div>
			<% end %>
		<% end %>
	<% end %> 
</div>

<% end %>

</div>

<script type="text/javascript">
	
	$('.show-map').click(function(){
		$('.map').toggle("fast");
		if($(this).html() == "Show on map"){
			$(this).html("Hide map");
			$(this).css("color", "#d1909b");
		} else {
			$(this).html("Show on map");
			$(this).css("color", "#90bbd1");
		}
	});

</script>