config/routes.rb
Rails.application.routes.draw do
  get 'index' => "events#index"

  get 'new' => "events#new", as: 'new_event'

  post 'new' => 'events#new'

  get 'edit/:id' => "events#edit", as: 'edit_event'

  post 'edit/:id' => 'events#edit'

  get 'event/:id' => "events#show", as: 'event'

  get 'profile' => 'pages#profile'

  get 'privacy' => 'pages#privacy'

  get 'terms' => 'pages#terms'

  delete 'delete/:id' => "events#destroy", as: 'destroy_event'

  patch 'event/:id' => "events#update"

  get 'confirmed' => 'pages#confirmed', as: 'confirmed'

 root 'events#index'

 resources :events

 devise_for :users, controllers: { confirmations: 'confirmations', omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations', passwords: 'passwords' }

  devise_scope :user do
    
    get 'login' => 'devise/sessions#new', as: 'login'

    post 'login' => 'devise/sessions#create'

    get 'register' => 'devise/registrations#new', as: 'register'

    post 'register' => 'devise/registrations#create'

    get 'profile/edit' => 'devise/registrations#edit', as: 'edit_user'

    get 'user/city' => 'registrations#city', as: 'add_city'

    get 'profile/password/edit' => 'registrations#edit_password', as: 'edit_password'

    patch 'user/password' => 'registrations#update_password' 

    patch 'user/city' => 'registrations#update_city'

    get 'password/reset' => 'passwords#new', as: 'password_reset'

    post 'password/reset' => 'passwords#reset_password'

    post 'email/confirmations' => 'confirmations#send_confirmation', as: 'send_reconfirmation'

    get 'email/confirmations' => 'confirmations#send_confirmation'

  end

  namespace :api, defaults: { format: :json } do
  namespace :v1 do
    devise_scope :user do
      #posts
      post 'register' => 'registrations#create'
      post 'login' => 'sessions#create'
      post 'facebook/login' => 'omniauth_callbacks#facebook'
      #puts
      put 'update' => 'registrations#update'
      #deletes
      delete 'logout' => 'sessions#destroy'
    end

    get 'email/:email' => 'miscs#email_search', :constraints => { :email => /.*/ }

    get 'events/:today/:city' => 'events#get_events'

    get 'event/show/:id' => 'events#show'

    post 'password/reset/:email' => 'miscs#reset_password', :constraints => { :email => /.*/ }

  end
  end
end

app/views/pages/confirmed.html.erb
<div class="page">

<div class='thank-you'>
THANK YOU!<br>
<span class="fa fa-check"></span>
</div>

<p>Thanks for verifying your email. You're the best!</p>


<% if !user_signed_in? %>
<%= link_to login_path, class: 'btn btn-primary confirmed-btn' do%>
 		Login
<% end %>

<% end %>
</div>

app/views/pages/privacy.html.erb
<h3>Privacy Policy</h3>

app/views/pages/profile.html.erb
<% if flash.now[:notice] %>
<div class="messages">
    <div class="alert alert-info">
    	<%= flash[:notice] %>
    </div>
</div>
<% end %>

<div class="profile">

<div class="info">
	<strong>Name: </strong><%= @name %><br>
	<strong>City: </strong><%= @city %><br>
<div>
	<% if !@user.provider? %>
		<%= link_to edit_password_path, class: 'btn btn-primary' do%>
	 		Edit Password
	 	<% end %>
	<% end %>

	<%= link_to edit_user_path, class: 'btn btn-primary' do%>
 		Edit Profile
 	<% end %>
</div>
</div>

<div class="feed">
<hr>

<div class="events">
	<%= render @events %>
</div>

<% if @events.count == 0 %>

	<div class='no-results'>You haven't posted any events yet</div>

<% end %>

<div class="pagination">
	<%= will_paginate @events %>
</div>

<% if @events.next_page %>
	<div id="load-more-posts" class="btn btn-primary"> Load more...</div>
<% end %> 
</div>
</div>

app/views/pages/profile.js.erb
$('.events').append('<%= j render @events %>');
<% if @events.next_page %>
   $('.pagination').replaceWith('<%= j will_paginate @events %>');
   $('.pagination').hide();
<% else %>
	$('.pagination').remove();
	$('#load-more-posts').remove();
<% end %>

app/views/pages/terms.html.erb
<h3>Terms of Use</h3>