config/routes.rb
Rails.application.routes.draw do
  get 'index' => "events#index"

  get 'new' => "events#new", as: 'new_event'

  post 'new' => 'events#new'

  get 'edit/:id' => "events#edit", as: 'edit_event'

  post 'edit/:id' => 'events#edit'

  get 'event/:id' => "events#show", as: 'event'

  get 'profile' => 'pages#profile'

  get 'privacy' => 'pages#privacy'

  get 'terms' => 'pages#terms'

  delete 'delete/:id' => "events#destroy", as: 'destroy_event'

  patch 'event/:id' => "events#update"

  get 'confirmed' => 'pages#confirmed', as: 'confirmed'

 root 'events#index'

 resources :events

 devise_for :users, controllers: { confirmations: 'confirmations', omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations', passwords: 'passwords' }

  devise_scope :user do
    
    get 'login' => 'devise/sessions#new', as: 'login'

    post 'login' => 'devise/sessions#create'

    get 'register' => 'devise/registrations#new', as: 'register'

    post 'register' => 'devise/registrations#create'

    get 'profile/edit' => 'devise/registrations#edit', as: 'edit_user'

    get 'user/city' => 'registrations#city', as: 'add_city'

    get 'profile/password/edit' => 'registrations#edit_password', as: 'edit_password'

    patch 'user/password' => 'registrations#update_password' 

    patch 'user/city' => 'registrations#update_city'

    get 'password/reset' => 'passwords#new', as: 'password_reset'

    post 'password/reset' => 'passwords#reset_password'

    post 'email/confirmations' => 'confirmations#send_confirmation', as: 'send_reconfirmation'

    get 'email/confirmations' => 'confirmations#send_confirmation'

  end

  namespace :api, defaults: { format: :json } do
  namespace :v1 do
    devise_scope :user do
      #posts
      post 'register' => 'registrations#create'
      post 'login' => 'sessions#create'
      post 'facebook/login' => 'omniauth_callbacks#facebook'
      #puts
      put 'update' => 'registrations#update'
      #deletes
      delete 'logout' => 'sessions#destroy'
    end

    get 'email/:email' => 'miscs#email_search', :constraints => { :email => /.*/ }

    get 'events/:today/:city' => 'events#get_events'

    get 'event/show/:id' => 'events#show'

    post 'password/reset/:email' => 'miscs#reset_password', :constraints => { :email => /.*/ }

  end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Okasion - Discover what's happening near you</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=530">
</head>
<body>
<nav class="navbar navbar-expand navbar-light bg-faded">

	<div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      	
        <% if !user_signed_in? %>
          <nav class="navbar navbar-light bg-faded mx-auto">
        <div class="navbar-brand">
          <%= image_tag('logo3.png', height: '38px') %>
        </div>
        </nav>

        <% else %>

        <div id="search-form">
          <%= form_tag events_path, :method => :get do %>
            <%= text_field_tag :search, params[:search], id:'search-field', class: 'location-field', placeholder: 'Search for a location' %>
            <%= button_tag(type: "submit", class: "btn btn-default search-btn", name: nil) do %>
                <i class="fa fa-search"></i>
            <% end %> 
          <% end %>
        </div>

        <div class="dropdown">
          <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="fa fa-bars"></span>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <%= link_to('Profile', profile_path, class: 'dropdown-item') %>

            <%= link_to('Create event', new_event_path, class: 'dropdown-item') %>

            <%= link_to('Home', root_path, class: 'dropdown-item') %>

                <div class="dropdown-divider"></div>

                <%= link_to('Privacy Policy', privacy_path, class: 'dropdown-item') %>

                <%= link_to('Terms of Use', terms_path, class: 'dropdown-item') %>
          
                <div class="dropdown-divider"></div>
            <%= button_to('Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item') %>
          </div>
        </div>

          <nav class="navbar navbar-light bg-faded">
          <%= link_to root_path, class: 'btn btn-default home-btn' do %>
            <span class="fa fa-home"></span>
          <% end %>
        </nav>
        
        <% end %>

	</div>
</nav>

<%= yield %>

<%= link_to '#', class: "btn btn-primary back-to-top-button" do %>
  <span class="fa fa-arrow-up">
<% end %>

<div class="scroll-top-val"></div>

<script type="text/javascript">
  function createCookie(name,value,days) {
    var expires = "";
    if (days) {
        var date = new Date();
        date.setTime(date.getTime() + (days*24*60*60*1000));
        expires = "; expires=" + date.toUTCString();
    }
    document.cookie = name + "=" + value + expires + "; path=/";
}
</script>

<script type="text/javascript">
  var date = new Date();
  var value = date.getTimezoneOffset();

  createCookie('time_zone', value / 60, 100);
</script>

</body>
</html>

<script type="text/javascript">
    function initMap() {
        var inputs = document.getElementsByClassName("location-field");
        var i;
        for (i = 0; i < inputs.length; i++) {
          var searchComplete = new google.maps.places.Autocomplete(inputs[i]);
        }
    }
</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY']%>&libraries=places&callback=initMap"></script>